version: '3.3'

services:

  app:
    container_name: app
    build: ./app
    volumes:
      - './app:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5000:5000'

  api:
    container_name: api
    build: ./api
    volumes:
      - './api:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4000:4000'

  webserver:
    container_name: webserver
    depends_on:
      - app
      - api
    image: nginx
    volumes:
      - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - '80:80'
    environment:
      - APP_HOST=app
      - APP_PORT=5000
      - API_HOST=api
      - API_PORT=4000
    command: /bin/bash -c "envsubst '$$APP_HOST, $$APP_PORT, $$API_HOST, $$API_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
