version: '3.3'

services:

  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - '5000:5000'
    hostname: webapp

  webserver:
    container_name: webserver
    image: nginx
    volumes:
     - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
     - '80:80'
    environment:
     - APP_HOST=webapp
     - APP_PORT=5000
    command: /bin/bash -c "envsubst '$$APP_HOST, $$APP_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
